name: Build Spring Boot Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bajaj-health-jar
        path: target/bajaj-health-1.0-SNAPSHOT.jar
        retention-days: 30
        
    - name: Show JAR Info
      run: |
        echo "JAR file created successfully!"
        ls -la target/
        echo "JAR size: $(du -h target/bajaj-health-1.0-SNAPSHOT.jar | cut -f1)"
